"""Initial migrations

Revision ID: 5d2881cd49ca
Revises:
Create Date: 2022-11-25 11:35:39.335733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2881cd49ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=80), nullable=False),
                    sa.Column('password_hash', sa.Text(), nullable=False),
                    sa.Column('access_token', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('ingredients', sa.Text(), nullable=True),
                    sa.Column('instructions', sa.Text(), nullable=True),
                    sa.Column('serving_size', sa.Float(), nullable=True),
                    sa.Column('category', sa.String(length=50), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('users')
    # ### end Alembic commands ###
